-- Create Categories table
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    name_ar TEXT,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Set up Row Level Security
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- Create policies
DROP POLICY IF EXISTS "Allow public read-only access" ON public.categories;
CREATE POLICY "Allow public read-only access" ON public.categories
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow admin full access" ON public.categories;
CREATE POLICY "Allow admin full access" ON public.categories
    FOR ALL USING (auth.role() = 'authenticated');

-- Seed initial categories if empty
INSERT INTO public.categories (name, name_ar)
SELECT name, name FROM (
    VALUES ('Sedan'), ('SUV'), ('Coupe'), ('Sports'), ('Luxury')
) AS t(name)
WHERE NOT EXISTS (SELECT 1 FROM public.categories);
